# Generated by Django 5.2.7 on 2025-11-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='飛行日期')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='結束時間')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='任務說明')),
                ('pilot_name', models.CharField(blank=True, max_length=20, verbose_name='飛行員')),
                ('recorder_name', models.CharField(blank=True, max_length=20, verbose_name='紀錄員')),
            ],
            options={
                'verbose_name': '飛行任務',
                'verbose_name_plural': '飛行任務',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='病蟲害名稱')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
            ],
            options={
                'verbose_name': '病蟲害種類',
                'verbose_name_plural': '病蟲害種類',
            },
        ),
        migrations.CreateModel(
            name='TeaGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='茶園名稱')),
                ('location_desc', models.CharField(blank=True, max_length=50, verbose_name='地點')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='飛行日期')),
                ('altitude_m', models.FloatField(blank=True, null=True, verbose_name='海拔高度(公尺)')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='長(公尺)')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='寬(公尺)')),
                ('area_sqm', models.FloatField(blank=True, null=True, verbose_name='面積(平方公尺)')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '茶園資訊',
                'verbose_name_plural': '茶園資訊',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='照片檔案')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='拍攝時間')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='高度(公尺)')),
                ('camera_make', models.CharField(blank=True, max_length=50, verbose_name='相機品牌')),
                ('camera_model', models.CharField(blank=True, max_length=50, verbose_name='相機型號')),
                ('focal_length_mm', models.FloatField(blank=True, null=True, verbose_name='焦距(mm)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='tea_app.flight', verbose_name='飛行任務')),
                ('garden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='tea_app.teagarden', verbose_name='茶園')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
            },
        ),
        migrations.CreateModel(
            name='PestDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.FloatField(blank=True, null=True, verbose_name='框左上 X')),
                ('y_min', models.FloatField(blank=True, null=True, verbose_name='框左上 Y')),
                ('x_max', models.FloatField(blank=True, null=True, verbose_name='框右下 X')),
                ('y_max', models.FloatField(blank=True, null=True, verbose_name='框右下 Y')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='模型信心度')),
                ('model_version', models.CharField(blank=True, max_length=50, verbose_name='模型版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='偵測時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='tea_app.pestcategory', verbose_name='病蟲害種類')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_detections', to='tea_app.photo', verbose_name='照片')),
            ],
            options={
                'verbose_name': '病蟲害偵測結果(YOLO)',
                'verbose_name_plural': '病蟲害偵測結果(YOLO)',
            },
        ),
        migrations.CreateModel(
            name='PestObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='發現時間')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='高度(公尺)')),
                ('severity', models.IntegerField(default=1, verbose_name='嚴重度(1~5)')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('closeup_photo', models.ImageField(blank=True, null=True, upload_to='pest_photos/', verbose_name='近拍照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='tea_app.pestcategory', verbose_name='病蟲害種類')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pest_observations', to='tea_app.flight', verbose_name='飛行任務')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_observations', to='tea_app.teagarden', verbose_name='茶園')),
            ],
            options={
                'verbose_name': '病蟲害觀察紀錄',
                'verbose_name_plural': '病蟲害觀察紀錄',
                'ordering': ['-observed_at'],
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='tea_app.teagarden', verbose_name='茶園'),
        ),
        migrations.CreateModel(
            name='YieldRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('area_sqm', models.FloatField(blank=True, null=True, verbose_name='面積(平方公尺)')),
                ('actual_yield_kg', models.FloatField(blank=True, null=True, verbose_name='實際產量(kg)')),
                ('predicted_yield_kg', models.FloatField(blank=True, null=True, verbose_name='預測產量(kg)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='代表點緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='代表點經度')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_records', to='tea_app.teagarden', verbose_name='茶園')),
            ],
            options={
                'verbose_name': '產量紀錄',
                'verbose_name_plural': '產量紀錄',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='YieldFeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_ratio', models.FloatField(blank=True, null=True, verbose_name='茶樹覆蓋率(0~1)')),
                ('mean_green_value', models.FloatField(blank=True, null=True, verbose_name='平均綠度')),
                ('texture_score', models.FloatField(blank=True, null=True, verbose_name='紋理指標')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yield_feature_snapshots', to='tea_app.flight', verbose_name='飛行任務')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_feature_snapshots', to='tea_app.teagarden', verbose_name='茶園')),
                ('photos', models.ManyToManyField(blank=True, related_name='yield_feature_snapshots', to='tea_app.photo', verbose_name='相關照片')),
                ('yield_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_snapshots', to='tea_app.yieldrecord', verbose_name='對應產量紀錄')),
            ],
            options={
                'verbose_name': '產量特徵快照',
                'verbose_name_plural': '產量特徵快照',
            },
        ),
    ]
