# Generated by Django 5.2.7 on 2025-11-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='天氣')),
                ('description', models.TextField(blank=True, verbose_name='詳細說明')),
            ],
            options={
                'verbose_name': '天氣',
                'verbose_name_plural': '天氣',
            },
        ),
    ]
