# Generated by Django 5.2.7 on 2025-11-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0003_flight_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='camera_make',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='camera_model',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='focal_length_mm',
        ),
        migrations.AlterField(
            model_name='flight',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='tea_app.weather', verbose_name='天氣'),
        ),
    ]
