# Generated by Django 5.2.7 on 2025-11-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0004_remove_photo_camera_make_remove_photo_camera_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='照片檔案'),
        ),
    ]
