# Generated by Django 5.2.7 on 2025-11-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0005_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestobservation',
            name='confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='模型信心度'),
        ),
    ]
