# Generated by Django 5.2.7 on 2025-11-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0006_pestobservation_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yieldfeaturesnapshot',
            name='coverage_ratio',
        ),
        migrations.RemoveField(
            model_name='yieldfeaturesnapshot',
            name='mean_green_value',
        ),
        migrations.RemoveField(
            model_name='yieldfeaturesnapshot',
            name='texture_score',
        ),
        migrations.AlterField(
            model_name='yieldfeaturesnapshot',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='yield_feature_snapshots', to='tea_app.photo', verbose_name='相關照片集'),
        ),
    ]
