# Generated by Django 5.2.7 on 2025-11-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0007_remove_yieldfeaturesnapshot_coverage_ratio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yieldfeaturesnapshot',
            options={'verbose_name': '產量特徵照片', 'verbose_name_plural': '產量特徵照片'},
        ),
        migrations.AddField(
            model_name='flight',
            name='times',
            field=models.FloatField(blank=True, null=True, verbose_name='批次'),
        ),
    ]
