# Generated by Django 5.2.7 on 2025-11-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0008_alter_yieldfeaturesnapshot_options_flight_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='times',
            field=models.IntegerField(blank=True, null=True, verbose_name='批次'),
        ),
    ]
