# Generated by Django 5.2.7 on 2025-11-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0011_alter_flight_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='description',
            field=models.TextField(blank=True, verbose_name='任務說明'),
        ),
    ]
