# Generated by Django 5.2.7 on 2025-11-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0012_alter_flight_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestcategory',
            name='description',
            field=models.CharField(blank=True, max_length=20, verbose_name='說明'),
        ),
    ]
