# Generated by Django 5.2.7 on 2025-11-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0013_alter_pestcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestdetection',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='pestdetection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pestdetection',
            name='model_version',
        ),
        migrations.RemoveField(
            model_name='pestdetection',
            name='x_max',
        ),
        migrations.RemoveField(
            model_name='pestdetection',
            name='x_min',
        ),
        migrations.RemoveField(
            model_name='pestdetection',
            name='y_max',
        ),
        migrations.RemoveField(
            model_name='pestdetection',
            name='y_min',
        ),
        migrations.AddField(
            model_name='pestobservation',
            name='model_version',
            field=models.CharField(blank=True, max_length=10, verbose_name='模型版本'),
        ),
    ]
