# Generated by Django 5.2.7 on 2025-11-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0014_remove_pestdetection_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='tea_app.weather', verbose_name='天氣'),
        ),
    ]
