# Generated by Django 5.2.7 on 2025-12-03 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0015_alter_flight_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestdetection',
            name='confidence',
            field=models.FloatField(default=0.0, verbose_name='信心度'),
        ),
        migrations.AddField(
            model_name='pestdetection',
            name='model_version',
            field=models.CharField(default='best.pt', max_length=100, verbose_name='模型版本'),
        ),
        migrations.AlterField(
            model_name='pestdetection',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='tea_app.pestcategory', verbose_name='類別'),
        ),
    ]
