# Generated by Django 5.2.7 on 2026-03-03 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0016_pestdetection_confidence_pestdetection_model_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='用戶名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '用戶',
                'verbose_name_plural': '用戶',
            },
        ),
        migrations.CreateModel(
            name='TenantMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='權限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
            ],
            options={
                'verbose_name': '租戶成員',
                'verbose_name_plural': '租戶成員',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='檔案SHA256'),
        ),
        migrations.AddField(
            model_name='photo',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='檔案大小(bytes)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='上傳者'),
        ),
        migrations.AddField(
            model_name='flight',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='tea_app.tenant', verbose_name='租戶'),
        ),
        migrations.AddField(
            model_name='photo',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tea_app.tenant', verbose_name='租戶'),
        ),
        migrations.AddField(
            model_name='teagarden',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to='tea_app.tenant', verbose_name='租戶'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['tenant', 'date'], name='tea_app_fli_tenant__788fb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('tenant', 'sha256'), name='uq_tenant_photo_sha256'),
        ),
        migrations.AddConstraint(
            model_name='teagarden',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_tenant_garden_name'),
        ),
        migrations.AddField(
            model_name='tenantmember',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tea_app.tenant'),
        ),
        migrations.AddField(
            model_name='tenantmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='tenantmember',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='uq_tenant_user_member'),
        ),
    ]
