# Generated by Django 5.2.7 on 2026-03-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0017_tenant_tenantmember_photo_sha256_photo_size_bytes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='description',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='recorder_name',
        ),
    ]
