# Generated by Django 5.2.7 on 2026-03-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0018_remove_flight_description_remove_flight_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestobservation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pestdetection',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pestdetection',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='pestobservation',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='pestobservation',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='yieldfeaturesnapshot',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='yieldfeaturesnapshot',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='yieldfeaturesnapshot',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='yieldfeaturesnapshot',
            name='yield_record',
        ),
        migrations.RemoveField(
            model_name='yieldrecord',
            name='note',
        ),
        migrations.AlterField(
            model_name='yieldrecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='yieldrecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='經度'),
        ),
        migrations.DeleteModel(
            name='PestCategory',
        ),
        migrations.DeleteModel(
            name='PestDetection',
        ),
        migrations.DeleteModel(
            name='PestObservation',
        ),
        migrations.DeleteModel(
            name='YieldFeatureSnapshot',
        ),
    ]
