# Generated by Django 5.2.7 on 2026-03-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0019_remove_pestobservation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_by',
        ),
    ]
