# Generated by Django 5.2.7 on 2026-03-04 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0020_remove_photo_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(default='best.pt', max_length=200)),
                ('conf_thres', models.FloatField(default=0.25)),
                ('iou_thres', models.FloatField(default=0.45)),
                ('status', models.CharField(default='done', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('elapsed_ms', models.IntegerField(blank=True, null=True)),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to='overlays/')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_runs', to='tea_app.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls_id', models.IntegerField()),
                ('cls_name', models.CharField(blank=True, default='', max_length=100)),
                ('conf', models.FloatField()),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='tea_app.inferencerun')),
            ],
        ),
        migrations.CreateModel(
            name='InferenceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('model_name', models.CharField(default='yolo', max_length=128)),
                ('model_conf', models.FloatField(default=0.25)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infer_jobs', to='tea_app.photo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tea_app.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='tea_app_inf_status_296022_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['photo', '-created_at'], name='tea_app_inf_photo_i_0d494b_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['run'], name='tea_app_det_run_id_7563d1_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['cls_id'], name='tea_app_det_cls_id_544816_idx'),
        ),
    ]
