# Generated by Django 5.2.7 on 2026-03-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0021_inferencerun_detection_inferencejob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='檔案SHA256'),
        ),
    ]
