# Generated by Django 5.2.7 on 2026-03-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0022_alter_photo_sha256'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='photo',
            name='uq_tenant_photo_sha256',
        ),
        migrations.AlterField(
            model_name='photo',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='檔案SHA256'),
        ),
    ]
