# Generated by Django 4.2.16 on 2026-03-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0023_remove_photo_uq_tenant_photo_sha256_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferencejob',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='inferencejob',
            name='tenant',
        ),
        migrations.AlterModelOptions(
            name='detection',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='inferencerun',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': '照片', 'verbose_name_plural': '照片'},
        ),
        migrations.RemoveIndex(
            model_name='inferencerun',
            name='tea_app_inf_photo_i_0d494b_idx',
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='bbox_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='median_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='mode',
            field=models.CharField(choices=[('normal', 'Normal YOLO'), ('sahi', 'SAHI')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='total_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sha256',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='檔案SHA256'),
        ),
        migrations.AlterField(
            model_name='tenantmember',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tea_app.tenant'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['photo', 'mode'], name='idx_run_photo_mode'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['created_at'], name='idx_run_created_at'),
        ),
        migrations.AddConstraint(
            model_name='inferencerun',
            constraint=models.UniqueConstraint(fields=('photo', 'mode'), name='uq_inference_run_photo_mode'),
        ),
        migrations.DeleteModel(
            name='InferenceJob',
        ),
    ]
