# Generated by Django 4.2.16 on 2026-03-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0024_remove_inferencejob_photo_remove_inferencejob_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='檔案SHA256'),
        ),
    ]
