# Generated by Django 4.2.16 on 2026-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0025_alter_photo_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencerun',
            name='area_cm2',
            field=models.FloatField(default=0, verbose_name='面積(cm²)'),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='density_g_per_cm2',
            field=models.FloatField(default=0, verbose_name='密度(g/cm²)'),
        ),
    ]
